#!/bin/sh


echo "Starting post-checkout hook ..."
BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)
CI_BUILD_STATUS_BADGE="[![Build Status](https://8435d1ad526d.ngrok.io/buildStatus/icon?job=github_public_renewlab%2F${BRANCH_NAME})](https://8435d1ad526d.ngrok.io/job/github_public_renewlab/job/${BRANCH_NAME}/)"
echo $BRANCH_NAME
echo $CI_BUILD_STATUS_BADGE

sed -i -e "/Build Status/ c $CI_BUILD_STATUS_BADGE" README.md
git add README.md
git commit -m "update CI build badge"

exit 0

