#!/bin/sh


echo "Starting pre-commit hook ..."
JENKINS_CI_BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)
JENKINS_BUILD_STATUS="[![Build Status](https://8435d1ad526d.ngrok.io/buildStatus/icon?job=github_public_renewlab%2F${JENKINS_CI_BRANCH_NAME})](https://8435d1ad526d.ngrok.io/job/github_public_renewlab/job/${JENKINS_CI_BRANCH_NAME}/)"
echo $JENKINS_CI_BRANCH_NAME
echo $JENKINS_BUILD_STATUS

sed -i -e "/Build Status/ c $JENKINS_BUILD_STATUS" README.md
git add REAMDME.md

exit 0


