#ifndef MACROS_H
#define MACROS_H

#define DEBUG_PRINT 0
#define DEBUG_RADIO 0
#define DEBUG_PLOT 0

#define EVENT_RX_SYMBOL 0

#define TASK_RECORD 0

// TASK & SOCKET thread number
#define TASK_THREAD_NUM 1
#define RX_THREAD_NUM 4

#define CORR_THRESHOLD 0x4
#define CORR_RST 0x0
#define CORR_SCNT 0x8
#define CORR_CONF 60
#define RF_RST_REG 48
#define TDD_CONF_REG 120
#define SCH_ADDR_REG 136
#define SCH_MODE_REG 140
#define TX_GAIN_CTRL 88

#define MAX_FRAME_INC 2000
#define TIME_DELTA 20 //ms

// Triggers - Used for Samples Offset Calibration
#define FPGA_IRIS30_TRIGGERS 44
#define FPGA_IRIS30_INCR_TIME (1 << 2)
#define FPGA_IRIS30_DECR_TIME (1 << 3)

// AGC and Packet Detect
#define FPGA_IRIS030_WR_AGC_ENABLE_FLAG	  232
#define FPGA_IRIS030_WR_AGC_RESET_FLAG 	  236
#define FPGA_IRIS030_WR_IQ_THRESH 	  240
#define FPGA_IRIS030_WR_NUM_SAMPS_SAT 	  244
#define FPGA_IRIS030_WR_MAX_NUM_SAMPS_AGC 248
#define FPGA_IRIS030_WR_RSSI_TARGET 	  252
#define FPGA_IRIS030_WR_WAIT_COUNT_THRESH 256
#define FPGA_IRIS030_WR_AGC_SMALL_JUMP 	  260
#define FPGA_IRIS030_WR_AGC_BIG_JUMP 	  264
#define FPGA_IRIS030_WR_AGC_TEST_GAIN_SETTINGS 268
#define FPGA_IRIS030_WR_AGC_GAIN_INIT     316

// RSSI register Set
#define FPGA_IRIS030_RD_MEASURED_RSSI 	  284

// Packet Detect Register Set
#define FPGA_IRIS030_WR_PKT_DET_THRESH 	  288
#define FPGA_IRIS030_WR_PKT_DET_NUM_SAMPS 292
#define FPGA_IRIS030_WR_PKT_DET_ENABLE	  296
#define FPGA_IRIS030_WR_PKT_DET_NEW_FRAME 300

#endif
