"""init

Revision ID: 3dc950cdbe38
Revises: 
Create Date: 2020-09-15 17:01:10.229903

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3dc950cdbe38'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('base_station_iris_temperature',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.String(length=30), nullable=True),
    sa.Column('servername', sa.String(length=30), nullable=True),
    sa.Column('iris_sn', sa.String(length=30), nullable=True),
    sa.Column('overheat_thresh', sa.String(length=30), nullable=True),
    sa.Column('lms7_temp', sa.String(length=30), nullable=True),
    sa.Column('zynq_temp', sa.String(length=30), nullable=True),
    sa.Column('tx_temp', sa.String(length=30), nullable=True),
    sa.Column('rx_temp', sa.String(length=30), nullable=True),
    sa.Column('overheat_warning', sa.Boolean(), nullable=True),
    sa.Column('error_warning', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_base_station_iris_temperature_timestamp'), 'base_station_iris_temperature', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_base_station_iris_temperature_timestamp'), table_name='base_station_iris_temperature')
    op.drop_table('base_station_iris_temperature')
    # ### end Alembic commands ###
